name: .NET Core

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      with:
        dotnet-version: 3.1.301
#     - name: Install dependencies
#       working-directory: ./OpenIdAuthNetCore
#       run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
